markdown: kramdown
highlighter: rouge

# Info
title: UofT Weblogging and Homebrew Website Club
email: uoftwebloggingclub@gmail.com
discord_invite: https://discord.gg/3uY2eRTAcn
instagram: weblogging.homebrew.club
google_calendar_code: ZjIxNzE2OWY5OWMzNDZkMjhhMmZmODFjMGNjNzM2ZGRlYzQwODc4NTE0ZmM1YzQ5NDE5ZWEyZGU0Mjc1ODczMEBncm91cC5jYWxlbmRhci5nb29nbGUuY29t
google_calendar_ical_link: https://calendar.google.com/calendar/ical/f217169f99c346d28a2ff81c0cc736ddec40878514fc5c49419ea2de42758730%40group.calendar.google.com/public/basic.ics

# Mark external links
target-blank:
    add_css_classes: external-link

# Jekyll Stuff
permalink: /blog/:slug
url: https://uoftwebloggingclub.neocities.org
baseurl: /

exclude:
  - README.md
  - runlocal.sh
  - generate_feed_json.rb
  - _members/example.md
  - scripts
  - Dockerfile
  - docker-compose.yml

collections:
  members:
    output: false
  events:
    output: true

feed:
  path: /announcements.xml

plugins:
  - jekyll-email-protect
  - jekyll-target-blank
  - jekyll-feed
  - liquid_reading_time
  - liquid_pluralize
  - jekyll-ical-tag
  - jekyll-timeago